#!/usr/bin/env bash
#
# Summary: Install the latest winetricks
#
# Usage: winenv winetricks
#        winenv winetricks --global
#        winenv winetricks --local
# Installs the latest winetricks globally or locally (--global by default)
#
set -e
[ -n "$WINENV_DEBUG" ] && set -x

if [ -z "$WINENV_ROOT" ]; then
    WINENV_ROOT="${HOME}/.winenv"
fi

# Provide winenv completions
command_prefix=winenv-overlay--
if [ "$1" = "--complete" ]; then
    declare -A commands
    for i in $WINENV_ROOT/libexec/$command_prefix*; do
        base=$(basename $i)
        command=${base##$command_prefix}
        commands[$command]=$command
    done

    if [[ -v "commands[$2]" ]]; then
        command="${commands[$2]}"
        command_path="$(command -v "$command_prefix$command")"
        exec "$command_path" --complete "${@:3}"
    else
        printf '%s\n' "${commands[@]}"
        exit 0
    fi
fi

command="$1"
case "$command" in
    "") echo "$(winenv-prefix-name) (set by $(winenv-prefix-origin))"
        ;;

    "--bare")
        echo "$(winenv-prefix-name)"
        ;;

    "-h" | "--help" )
        echo "print usage..."
        ;;

    *)  command_path="$(command -v "winenv-overlay--$command" || true)"
        if [ -z "$command_path" ]; then
            echo "winenv: no such command \`overlay $command'" >&2
            exit 1
        fi

        shift 1
        exec "$command_path" "$@"
        ;;
esac

usage() {
  # We can remove the sed fallback once winenv 0.4.0 is widely available.
  winenv-help install-winetricks 2>/dev/null || sed -ne '/^#/!q;s/.//;s/.//;1,4d;p' < "$0"
  [ -z "$1" ] || exit "$1"
}

#INSTALL_PREFIX="$(winenv-winenv-prefix)"
#WINENV_WINETRICKS_URL="https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
#WINENV_WINETRICKS_OUT="$INSTALL_PREFIX/bin/winetricks"

#curl -L "$WINENV_WINETRICKS_URL" -o "$WINENV_WINETRICKS_OUT"
#chmod +x "$WINENV_WINETRICKS_OUT"
#winenv rehash

#LOWER_DIR="${1:-/media/david/games/RAIDY/wine-prefix}"
#UPPER_DIR="${2:-/home/david/Desktop/tmp/ace-prefix}"
#MERGED_DIR="${3:-./merged}"
#WORK_DIR="$(mktemp -d)"

#LOWER_DIR="${1:-/media/david/games/RAIDY/wine-prefix}"
#UPPER_DIR="${2:-/home/david/Desktop/tmp/ace-prefix}"
#MERGED_DIR="${3:-./merged}"
#WORK_DIR="$(mktemp -d)"
