#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Perl version
#
# Usage: winenv shell <version>
#        winenv shell --unset
#
# Sets a shell-specific Perl version by setting the `WINENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Perl version known to winenv.
# The special version string `system' will use your default system Perl.
# Run `winenv versions' for a list of available Perl versions.

set -e
[ -n "$WINENV_DEBUG" ] && set -x

# Provide winenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec winenv-versions --bare
fi

version="$1"
shell="${WINENV_SHELL:-$SHELL}"
shell="${shell##*/}"

if [ -z "$version" ]; then
  if [ -z "$WINENV_VERSION" ]; then
    echo "winenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$WINENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e WINENV_VERSION"
    ;;
  * )
    echo "unset WINENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if winenv-winenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv WINENV_VERSION \"${version}\""
    ;;
  * )
    echo "export WINENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "return 1"
  exit 1
fi
