#!/usr/bin/env bash
# Summary: Explain how the current wine version is set
set -e
[ -n "$WINENV_DEBUG" ] && set -x

if [ -n "$WINENV_VERSION" ]; then
  echo "WINENV_VERSION environment variable"
else
  winenv-version-file
fi
