#!/usr/bin/env bash
# Summary: List all wine versions that contain the given executable
# Usage: winenv whence [--path] <command>

set -e
[ -n "$WINENV_DEBUG" ] && set -x

# Provide winenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec winenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  winenv-versions --bare | while read version; do
    path="$(winenv-winenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

WINENV_COMMAND="$1"
if [ -z "$WINENV_COMMAND" ]; then
  winenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$WINENV_COMMAND")"
[ -n "$result" ] && echo "$result"
