#!/usr/bin/env bash
# Summary: Detect the file that sets the current winenv version
set -e
[ -n "$WINENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.wine-version" ]; then
      echo "${root}/.wine-version"
      exit
    elif [ -e "${root}/.winenv-version" ]; then
      echo "${root}/.winenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$WINENV_DIR"
[ "$WINENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${WINENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${WINENV_ROOT}/global" ]; then
  echo "${WINENV_ROOT}/global"
elif [ -e "${WINENV_ROOT}/default" ]; then
  echo "${WINENV_ROOT}/default"
else
  echo "$global_version_file"
fi
