#!/usr/bin/env bash
# Usage: winenv version-file-write <file> <version>

set -e
[ -n "$WINENV_DEBUG" ] && set -x

WINENV_VERSION_FILE="$1"
WINENV_VERSION="$2"

if [ -z "$WINENV_VERSION" ] || [ -z "$WINENV_VERSION_FILE" ]; then
  winenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
winenv-winenv-prefix "$WINENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$WINENV_VERSION" > "$WINENV_VERSION_FILE"
