#!/usr/bin/env bash
# Summary: Show the current wine version and its origin
#
# Shows the currently selected wine version and how it was
# selected. To obtain only the version string, use `winenv
# version-name'.

set -e
[ -n "$WINENV_DEBUG" ] && set -x

echo "$(winenv-version-name) (set by $(winenv-version-origin))"
