#!/usr/bin/env bash
#
# Summary: Set or show the global wine prefix
#
# Usage: winenv global <prefix>
#
# Sets the global wine prefix. You can override the global prefix at
# any time by setting a directory-specific prefix with `winenv local'
# or by setting the `WINENV_PREFIX' environment variable.
#
# <prefix> should be a string matching a wine prefix known to winenv.
# The special prefix string `system' will use your default system wine.
# Run `winenv prefixs' for a list of available wine prefixs.

set -e
[ -n "$WINENV_DEBUG" ] && set -x

# Provide winenv completions
if [ "$1" = "--complete" ]; then
   exit 0
fi

WINENV_PREFIX="$($READLINK -f "$1")"
WINENV_PREFIX_FILE="${WINENV_ROOT}/prefix"

if [ -n "$WINENV_PREFIX" ]; then
  winenv-prefix-file-write "$WINENV_PREFIX_FILE" "$WINENV_PREFIX"
else
  winenv-prefix-file-read "$WINENV_PREFIX_FILE" ||
  winenv-prefix-file-read "${WINENV_ROOT}/global" ||
  winenv-prefix-file-read "${WINENV_ROOT}/default" ||
  echo system
fi
