#!/usr/bin/env bash
# Summary: Display the version of winenv
#
# Displays the version number of this winenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$WINENV_DEBUG" ] && set -x

version="2.3.1"

if cd "$WINENV_ROOT" 2>/dev/null; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "winenv ${git_revision:-$version}"
